apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db.yaml
  - ingress.yaml
  - cm.yaml
  - deployment.yaml
configMapGenerator:
  - name: init-sql
    files:
      - init.sql=init.sql
generatorOptions:
  disableNameSuffixHash: true
