services:
  postgres:
    image: postgres:16
    container_name: dev-postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: webapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../webapp-color/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  flask-app:
    build:
      context: ../webapp-color
      dockerfile: ../.devcontainer/Dockerfile-dev
    container_name: flask-app
    environment:
      uri: postgresql://dev:dev@postgres:5432/webapp
      STATEFUL: false
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ../webapp-color:/app
    command: ["sleep", "infinity"]

volumes:
  postgres-data:
