# Usa l'immagine base ufficiale per Python da VS Code Dev Containers
FROM mcr.microsoft.com/vscode/devcontainers/python:3.12

# Installa eventuali dipendenze di sistema
RUN apt-get update && apt-get install -y \
    build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Expose Flask port only
EXPOSE 8080

# Imposta la directory di lavoro
WORKDIR /workspace

# Copia il file delle dipendenze e installa i pacchetti Python
# COPY requirements.txt .
# RUN pip install --upgrade pip && pip install -r requirements.txt

# Copia tutti i file del progetto
COPY . .
