name: Build docker image and Deploy to kubernetes

on:
  workflow_dispatch:
  push:
    branches: 
      - "main"
    paths:
      - 'webapp-color/**'
      - '.github/**'
  pull_request:
    branches:
      - main
    paths:
      - 'webapp-color/**'
env:
  IMAGE_NAME: "webapp-color"
  REGISTRY: "ghcr.io"

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    name: build
    steps:
    - uses: actions/checkout@v4
    - name: downcase imagename
      run: |
        GENIMAGEPATH=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        echo "FULLIMAGEURI=${GENIMAGEPATH,,}" >>${GITHUB_ENV}
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ env.FULLIMAGEURI}}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=${{github.run_number}}
        flavor: |
          latest=auto
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: webapp-color
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Copy init.sql to k8s folder
      run: cp webapp-color/init.sql webapp-color/k8s/

    - uses: alexellis/arkade-get@master
      with:
        kubectl: latest
        kustomize: latest

    - name: Setup kubeconfig
      uses: azure/k8s-set-context@v4
      with:
        method: 'kubeconfig'
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - uses: cschleiden/replace-tokens@v1.3
      with:
        files: '["webapp-color/k8s/*.yaml"]'
      env:
        USERHOSTNAME: ${{ secrets.NAMESPACE }}
        FULLIMAGENAME: ${{ env.FULLIMAGEURI }}

    - name: Bake deployment
      uses: azure/k8s-bake@v3
      with:
        renderEngine: 'kustomize'
        kustomizationPath: 'webapp-color/k8s'
        kubectl-version: 'v1.30.0'
      id: bake

    - name: Deploy
      uses: azure/k8s-deploy@v5
      with:
        namespace: ${{ secrets.NAMESPACE }}
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: '${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{github.run_number}}'
